# Generated by Django 4.0.5 on 2022-06-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_place1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place1',
            name='name1',
            field=models.CharField(max_length=251),
        ),
    ]
