# Generated by Django 4.0.5 on 2022-06-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_place1_name1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place1',
            new_name='Place2',
        ),
    ]
